### PR TITLE
clients: Update Kaidan

### PR DESCRIPTION
**Pull request by melvo**

### CODE REVIEW

**Comment by bascht** [comment]
@melvo Thanks for the PR! It looks like it's merged for [qxmpp](https://github.com/qxmpp-project/qxmpp/commit/ceb62dd9d0d86bc8327ace116930962cf7fad1e9) but not yet available for Kaidan itself – at least the [upstream issue](https://invent.kde.org/network/kaidan/-/issues/254) is still open, no?

**Comment by melvo** [comment]
@bascht Yes. I will remove *WIP* from the title as soon as Kaidan supports it as well.

**Comment by bascht** [comment]
@melvo oooh, so you're using GitLab features over at GitHub. :grin:

**Comment by melvo** [comment]
@bascht Ah :D

**Comment by melvo** [comment]
@bascht Kaidan supports OMEMO now :)

**Comment by melvo** [comment]
@bascht Could you please merge this?

**Comment by melvo** [comment]
@bascht Thanks!

**Pull request merged**
