### PR TITLE
Add Swift

### PR DESCRIPTION
**Pull request by alexara**

### CODE REVIEW

**Comment by ReneVolution** [comment]
Is that about https://swift.im ? Do you have any info on the OMEMO integration status?

**Comment by alexara** [comment]
There was a question today on `swift@rooms.swift.im` at 12:06 pm.
Tobias anwered, "some form of end-to encryption (likely OMEMO) is on the rough roadmap, but we don't have a timeline for that".

**Comment by ReneVolution** [comment]
i see. so at least nothing in active development. hmm ... we need to think on how we want to represent all those messenger.

**Comment by bascht** [comment]
@alexara Nevertheless – having it in here is better than nothing. 😄 Could you rebase it again?

**Pull request merged**
