### PR TITLE
Set the progress of Movim to zero and (or) remove it completely, also remove Zom from the list of clients that could use Smack

### PR DESCRIPTION
**Pull request by tdemin**
See [this comment][comment]. @edhelas is not going to implement OMEMO in Movim.
It's probably even better to completely remove Movim from the list.

[comment]: https://github.com/movim/movim/issues/63#issuecomment-328371526

### CODE REVIEW

**Comment by edhelas** [comment]
I'm fine with removing Movim from the list, thanks :)

**Comment by bascht** [comment]
I think it would be better if we leave Movim in the list and document @edhelas' decision (which I find completely reasonable). Otherwise we'll have the next "Add Movim to the list" pull request coming up in a few months. 
We also list Coy, even [as they spoke out against adding OMEMO](https://github.com/twstrike/coyim/issues/421). 😄

**Comment by tdemin** [comment]
@bascht what about merging only the first commit then? 😉

**Comment by bascht** [comment]
@tdemin Yup. I've cherry-picked a7eadd6 onto master. Thanks! :smil

**Pull request closed without merging**
