### PR TITLE
Update client_row.html

### PR DESCRIPTION
**Pull request by Echolon**
Somehow the pause_button :pause_button: cannot be put in the code as the others :/

### CODE REVIEW

**Comment by bascht** [comment]
@Echolon have you tried inserting the actual Emoji? (e.g. copying it from here: https://emojipedia.org/apple/ios-9.3/double-vertical-bar/) That's how I got the others in there.

**Comment by Echolon** [comment]
Problem was that Github showed it for a second, than erased it. Maybe its a browser problem... will try again tomorrow

**Comment by Echolon** [comment]
@bascht how can I tell travis to rerun again?

**Comment by bascht** [comment]
@Echolon I've resolved the conflict via the GitHub UI – can you re-check if you're still okay with the change?

**Comment by Echolon** [comment]
I took this with relation to the development in general. So that development of a client is treated as inactive.

but is fine, not important

**Pull request merged**
