### PR TITLE
Add slixmpp library

### PR DESCRIPTION
**Pull request by Ppjet6**
Not entirely sure how you want to use the progress bar. I just copied it from Sleekxmpp.

It is not released yet.
It supports:
- Decryption
- Encryption to any arbitrary number of JIDs. (1:1 and MUCs)
- Trust management (wrapper for the [omemo backend](https://github.com/syndace/python-omemo))

It doesn't yet support aesgcm.

I've been meaning to make a first alpha release for 2 weeks already. Any time now..

Signed-off-by: Maxime “pep” Buquet <pep@bouah.net>

### CODE REVIEW

**Comment by bascht** [comment]
Hi @Ppjet6! Thanks for the PR. It's good to have it in there, so I'm gonna merge it right away.

If I understand it correctly, it will probably be on-par with Poezio ?

**Comment by Ppjet6** [comment]
Hey! Thanks for merging!

Sorry I did not understand your comment on Poezio.
Poezio uses slixmpp, what needs to be done after that is the UI bits!

The slixmpp plugin is now released at https://lab.louiz.org/poezio/slixmpp-omemo, I guess I could PR that as well.

**Comment by bascht** [comment]
@Ppjet6 Sorry, my English was a bit off there. :smile: What I wanted to ask is: As Poezio uses slixmpp the OMEMO progress on both will be the same, no?

**Comment by Ppjet6** [comment]
@bascht, when there is a `poezio-omemo` plugin using `slixmpp-omemo`, probably yes. at the moment there is not `poezio-omemo` at all :)

**Pull request merged**
