### PR TITLE
Add Psi and Psi+ to the list.

### PR DESCRIPTION
**Pull request by bowlofeggs**

### CODE REVIEW

**Comment by ReneVolution** [comment]
Hey there, do you have any status info on the OMEMO integration for Psi Psi+.

**Comment by bowlofeggs** [comment]
@ReneVolution I don' tknow what the status is, I just wanted to get them into the list. Unfortunately for me, a lot of the Psi+ docs are written in Russian and I don't know that language ☺

**Comment by bowlofeggs** [comment]
I just found this: https://github.com/psi-plus/plugins/issues/10

**Comment by ReneVolution** [comment]
Oh yeah ... just saw that. Could you add the issue link for the pull request?

**Comment by bowlofeggs** [comment]
Sure!

**Comment by bowlofeggs** [comment]
Added the tracker for Psi+ and rebased. I'm not sure what Psi is. Is it just an older version of Psi+, or is Psi+ a fork? Is Psi active?

**Comment by bascht** [comment]
Interesting indeed. Psi+ is on [Sourceforge](https://sourceforge.net/projects/psiplus/files/) and looks active, and Psi is active on [GitHub](https://github.com/psi-im/psi) – only the website looks dead: http://psi-im.org/

@ReneVolution Merge away! :shipit:

**Comment by ReneVolution** [comment]
Here the merge train comes!

**Comment by Neustradamus** [comment]
Psi: https://github.com/psi-im/psi/issues/252

Psi+: https://github.com/psi-plus/main/issues/673
Psi+: https://github.com/psi-plus/plugins/issues/10

**Comment by Neustradamus** [comment]
For all people, have you updated your Psi/Psi+?

I would like feedbacks from all users for OMEMO:
- Between Psi, Psi+, and other OMEMO XMPP clients
- OMEMO detection (grey icon / color icon)
- Secure chat (1:1)
- Secure mucroom
- New fingerprints detection
- OMEMO option possibilities (Options->Plugins->OMEMO options), all are good?
-- "Clear devices" and "Refresh" buttons in "Manage Devices" are missing (https://github.com/psi-im/plugins/issues/38)
-- Impossible to remove fingerprints of contacts (https://github.com/psi-im/plugins/issues/37)
-- Regenerate "Own fingerprint" is missing (https://github.com/psi-im/plugins/issues/36)

In the same time:
- OTR feedback too
- GnuPG feedback too

Thanks in advance.

**Pull request merged**
