### PR TITLE
Design proposal ReneVolution

### PR DESCRIPTION
**Pull request by ReneVolution**
As i liked the design very much before, here is an alternative approach to initially sort by Done, Testing and WIP in sequence. Even it is a little "hacky", it maintains the nice design 😸

### CODE REVIEW

**Comment by DreamFlasher** [comment]
Do you have a preview? 
I guess design is just very subjective, but I'm a big fan of simplicity. And one column is simpler than 3 (or 4 with date)...

**Comment by ReneVolution** [comment]
Here you go:
screen shot 2017-02-20 at 02 34 52

I think having a single timestamp does not visualise the status of a project properly.

**Comment by DreamFlasher** [comment]
Thank you! I agree that a single timestamp is not enough, that's why my suggestion is status + timestamp. 
The three column layout contains 2/3 of duplicate information: If a project is done then well it was work in project before and tested. If a project is not yet in progress then it's unlikely to be finished. 
On the other hand three columns with different width look just ugly... Why not a progress bar icon to have the best from both worlds?

**Comment by ReneVolution** [comment]
Indeed, a progress bar sounds promising, though even that does not give all the info i'd like to see there, e.g. stalled, not-gonna-happen, etc. 😄 

For the data structure though, i'd propose a `status` mapping:

0 => Not gonna happen
1 => In Progress
2 => Testing
3 => Done
4 => Development stalled

... add missing.

**Comment by ReneVolution** [comment]
Maybe even better for sorting by status:

0 => Done
1 => Testing
2 => Work in Progress
3 => Development stalled
4 => Not gonna happen

**Comment by ReneVolution** [comment]
Ok, no ... this seems better:

0 => Not gonna happen
15 => Development stalled
33 => Work in Progress
66 => Testing
100 => Done

That fits much better the standard progress bar scale.

**Comment by DreamFlasher** [comment]
I think a status in integers is a good idea, yes. How about 1 to 10?
0 => not gonna happen
2 => development stalled
4 => wip
7 => testing
10 => done

**Comment by ReneVolution** [comment]
Would that be the option?

screen shot 2017-02-20 at 13 05 42

**Comment by DreamFlasher** [comment]
Way nicer! Is it sortable? (doesn't look like it).

**Comment by ReneVolution** [comment]
It is sortable ... but has a bug when sorting for some unknown reason. Will need to debug it.

**Comment by ReneVolution** [comment]
Fixed the sorting ... so that would work ...

screen shot 2017-02-20 at 13 32 28

**Comment by DreamFlasher** [comment]
It looks very nice -- I still would find it nice if Conversations would be on the first position, and Gajim on the second, to give them their deserved fame...

**Comment by ReneVolution** [comment]
Slightly change in the progress bar style.

screen shot 2017-02-20 at 13 40 17

I'm all in for giving fame to first adopters ... we'd need another field then specifically for sorting on a different level, at least for the initial sort. Need to think about that.

**Comment by DreamFlasher** [comment]
Hmm, how about release date? *fg*

**Comment by ReneVolution** [comment]
Implementing something only to make sure some specific messengers are always on top feels like some hidden advertisement. Not entirely sure how i feel about that. They both deserve their fame 😸, but maybe this site is not the right place for such advertisement.

**Comment by DreamFlasher** [comment]
Well, it's not only about the two, I see omemo.top also as an information page that goes beyond done/not done. And having an overview of the history is quite nice imho.

**Comment by bascht** [comment]
@ReneVolution @DreamFlasher So – how about  I merge this branch so we have the progress bars & I add the details in #40  ?

**Comment by ReneVolution** [comment]
Good with me 😺

**Comment by DreamFlasher** [comment]
works for me :) So will you add a date column to sort on? *g*

**Comment by bascht** [comment]
@drea I might consider it later ;)

**Comment by DreamFlasher** [comment]
@bascht that's a no ;)

**Comment by bascht** [comment]
@DreamFlasher It's a rather diplomatic way of saying »I'd like to keep the complexity of the front page at a minimum. 😏  Dates might make it into #40.

**Comment by DreamFlasher** [comment]
I do prefer a no with a reason over diplomatic BS ;)

**Comment by bascht** [comment]
As I said: I want to keep the complexity of the frontpage at a minimum. So: I don't want it to have a date column, whereas I'm perfectly fine with dates in the detail pages.

**Comment by DreamFlasher** [comment]
? I didn't disagree on what you said. I just wanted to point out that it's better to directly say things instead of diplomatic BS :)

**Comment by bascht** [comment]
I think you made your point.

**Pull request merged**
