### PR TITLE
ChatSecure is not 100%

### LINKED ISSUE #70: ChatSecure is not 100%
ChatSecure doesn't support OMEMO in MUC: https://github.com/ChatSecure/ChatSecure-iOS/issues/580 and has issues with OMEMO file transfer (it is not working): https://github.com/ChatSecure/ChatSecure-iOS/issues/810

### PR DESCRIPTION
**Pull request by mimi89999**
Closes #70

### CODE REVIEW

**Comment by mimi89999** [comment]
@bascht Please review.

**Comment by bascht** [comment]
@mimi89999 What about Pidgin? Can you or @DreamFlasher confirm whether MUC / File Upload works with Lurch?

**Comment by mimi89999** [comment]
@bascht I ashed in the Conversations MUC about that. Got this answer:
> ‎[18:44:22] ‎rdm‎: mimi89999, i use both both conversations and pidgin with omemo on  one account it works 100 % without any issue...even with lurch  i find omemo management is more functional than  in any other xmpp clients ..and it works flawlessly with message carbons too.

**Comment by bascht** [comment]
Whoa, nice. I always though Pidgin kind of EOL'ed because _something something libpurple_ 😄

**Comment by DreamFlasher** [comment]
Yeah actually lurch should be listed instead of the other plugin, or we could even list both. I didn't get message carbons working, my current state was, that it's not supported by Pidgin?

**Comment by bascht** [comment]
I think there is another Plugin that bolts Message Carbons onto Pidgin, no?

**Comment by evaryont** [comment]
There is another plugin that adds carbons support to Pigin, written by the same author even! https://github.com/gkdr/carbons

**Pull request merged**
