### PR TITLE
add Jappix, Movim, PRISM Break, Chat Core, Kaiwa, Converse.js, Monal, JSXC, Kontalk

### PR DESCRIPTION
**Pull request by DreamFlasher**

### CODE REVIEW

**Comment by LeSpocky** [comment]
Kontalk and Movim are already on the list. Did you check for duplicates? Maybe #21 could help here? ;-)

**Comment by LeSpocky** [comment]
Also you mixed updating bounties, which is now also covered by #25, and adding things to the list.

**Comment by DreamFlasher** [comment]
Yup, this includes a bunch of updates :)
I did check on duplicates, but apparently didn't find all of them :) Will update the PR.

**Comment by bascht** [comment]
Thanks for the Update, sorry for the lag! 👍 😃

**Comment by DreamFlasher** [comment]
no worries, it's a pleasure to help!

**Pull request merged**
