### PR TITLE
[Salut à Toi] Updated status

### PR DESCRIPTION
**Pull request by goffi-contrib**
OMEMO implementation is now complete in SàT (one2one, MUC and files).

### CODE REVIEW

**Comment by goffi-contrib** [comment]
@bascht hi, is this website still maintained? Is is possible to merge this PR? I see that there are other also waiting, like poezio. Thanks!

**Comment by goffi-contrib** [comment]
@bascht is there anybody still checking PR ?

**Comment by goffi-contrib** [comment]
@Echolon pinging you too, as it seems that you have merge rights too. Thanks!

**Comment by bascht** [comment]
@goffi-contrib thank you! I've had to follow up with a few other PRs first, so I am rebasing yours onto master and merging it over at my repo! :)

**Comment by bascht** [comment]
Closed via ee7f40aa26085a54abac242bfca456d37bacbf6e

**Comment by bascht** [comment]
@goffi-contrib I think I accidentally pulled in an old commit from your master branch: 6a989d63408fe17badedc0053197732e323cae0c can you verify that the final file is still alright?

**Comment by goffi-contrib** [comment]
@bascht it looks fine, thanks!

**Comment by Echolon** [comment]
@goffi-contrib sorry was on holiday :wink: 

I guess everything is done, or?

**Comment by goffi-contrib** [comment]
@Echolon yes it's fine now, thanks :)

**Pull request closed without merging**
