### PR TITLE
fix tracking_issue url

### PR DESCRIPTION
**Pull request by cyBea**

### CODE REVIEW

**Comment by bascht** [comment]
@cyBea Sorry for the long wait. Just got around to review this. It looks like it is a private GitLab instance now – at least I couldn't access the ticket status. Neither the old nor the new one :worried:

**Comment by selurvedu** [comment]
@bascht this is probably a publicly accessible URL: https://invent.kde.org/kde/kaidan/issues/254
At least the issue number and description matches, not sure about the comments & other stuff.

**Comment by bascht** [comment]
@selurvedu yip, this looks better.
@cyBea can you update the PR? :smile:

**Comment by bascht** [comment]
Kaidan since moved again to a new sub-project, I updated it one last time. ;-)

**Pull request merged**
