### PR TITLE
add client omemo instant messenger 

### PR DESCRIPTION
**Pull request by froghorn82**
Please add new conversations fork omemo.im to your clients list.
url: https://omemo.im/
github: https://github.com/froghorn82/omemo-im/

### CODE REVIEW

**Comment by bascht** [comment]
@froghorn82 thank you for your PR. I think you based it upon the wrong branch / an outdated commit. Did you have a local branch prepared with the changes?

**Comment by froghorn82** [comment]
> @froghorn82 thank you for your PR. I think you based it upon the wrong branch / an outdated commit. Did you have a local branch prepared with the changes?

@bascht Thanks for your reply. Sorry about that but I just wanted to add my new client to your omemo.top list please.

**Comment by bascht** [comment]
@Echolon I'm a bit confused as well. I thought this PR was about Chatty, but it is about "OMEMO IM" at https://github.com/froghorn82/omemo-im/

@froghorn82 I've searched through your commits and I could not find a single commit from you that would add your client to the list. Could you please re-check your pull request? Thanks! :smile:

**Comment by evaryont** [comment]
@bascht I think this one can be closed.

**Comment by bascht** [comment]
@evaryont Yip, you're right.

@froghorn82 please re-open a new PR if we missed something.

**Pull request closed without merging**
