### PR TITLE
Update the progress of Psi+

### PR DESCRIPTION
**Pull request by tdemin**
Looks like Psi+ now [has a working plugin](https://github.com/psi-im/plugins/issues/10#issuecomment-361011306) for OMEMO. It's still WIP, though, but it's already a huge progress!

🎉

### CODE REVIEW

**Comment by bascht** [comment]
Neaaat. Does this to apply to the regular `Psi` as well? I've scrolled through the PR but it's not totally clear to me.

**Comment by tdemin** [comment]
@stigger, could you please tell if this is compatible with the regular Psi? 😃

**Comment by stigger** [comment]
@tdemin Yes, it is compatible.

**Comment by tdemin** [comment]
@bascht 🎉  😄 💪

**Comment by tdemin** [comment]
Since the actual tracking happens in another issue, I've also updated the tracking issue link. See 3d3e5aa

**Comment by bascht** [comment]
@tdemin @stigger thank you! 👍

**Comment by Neustradamus** [comment]
I am very happy about the work of @stigger for Psi/Psi+

Issue: https://github.com/psi-plus/main/issues/673

**Pull request merged**
