### PR TITLE
Shall we link to XEP-0384 instead?

### PR DESCRIPTION
**Pull request by saper**
Speaking of which - do we mean XEP-0384 conformance? earlier draft?

### CODE REVIEW

**Comment by bascht** [comment]
I think I would rather link to both – so: Keep the link to the nice landing page on conversations.im and add a link to the XEP for those who know what a XEP even is. :smile:

**Comment by saper** [comment]
Ouch, you are right, I was under impression there was a link to the possibly now obsoleted draft.

**Comment by bascht** [comment]
@saper Feel free to change the MR to something like "As of 07.12.2016, the OMEMO is accepted as an official XMPP standard XEP-0384…" or so. :)

**Comment by Echolon** [comment]
@saper I'm following up on this. Is your commit complete your did @bascht ask you to a change. I only see one link, but you both discussed to add two?

**Comment by saper** [comment]
nevermind, so much red tape for such a simple thing...

**Comment by bascht** [comment]
In case the branch get's pushed again this should reopen on it's own.

**Pull request closed without merging**
